const urls = {
  langListUrl: '/umv1/langs/lists',
  userLoginUrl: '/umv1/user/login',
  userLogoutUrl: '/umv1/user/logout',
  userInfoUrl: '/umv1/user/info',
  courseLangsUrl: '/capiv1/course/list',
  sendCodeUrl: '/umv1/sms/send',
  uploadUserPhotoUrl: '/user/upload_user_photo',
  teacherInfoUrl: '/baiban/teacher/edit',
  uploadTokenUrl: '/qiniu_token/uploadfiles',
  editUserPhotoUrl: '/baiban/users/edit_photo',
  updateUserNicknameUrl: '/baiban/users/edit_nickname',
  updateTeacherInfoUrl: '/baiban/teacher/update',
  addTeacherInfoUrl: '/baiban/teacher/create',
  liveCourseListUrl: '/baiban/live_course/list',
  findUserSignUrl: '/baiban/user_sig/find',
  moduleListUrl: '/baiban/course_module/list',
  imUserTokenUrl: '/imv1/user/token',
  liveCommentUrl: '/disv1/live/comment',
  createFilesTranscodeUrl: '/baiban/course_files/create_transcode',
  describeTranscodeUrl: '/baiban/course_files/describe_transcode',
  delCourseFileUrl: '/baiban/course_files/delete_file',
  courseFileListUrl: '/baiban/course_files/list',
  liveCourseRoomIdUrl: '/baiban/live_course/room_id',
  startOnlineRecordUrl: '/baiban/course_videos/start_online_record',
  stopOnlineRecordUrl: '/baiban/course_videos/stop_online_record',
  describeOnlineRecordUrl: '/baiban/course_videos/describe_online_record',
  createIMGroupUrl: '/baiban/groups/creates',
  destroyIMGroupUrl: '/baiban/groups/destroy',
  liveCourseOnlineUrl: '/baiban/live_course/online',
  liveCourseOfflineUrl: '/baiban/live_course/offline',
  liveCommentListUrl: '/disv1/live/comment/list',
};

export default urls;
